version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: donnees globales greenweez
    tables: 

      - name: sales
        identifier: raw_gz_sales
        description: sales of grenweez

      - name: product
        identifier: raw_gz_product
        description: infos sur les produits
        test: 
          - unique
             column_name: "products_id" 
         
        

      - name: ship
        identifier: raw_gz_ship
        description: infos logistiques
          test: 
          - unique
             column_name: "orders_id" 
         
